### PR TITLE
Numerous improvements

### PR DESCRIPTION
**Pull request by Raynos**
Sorry, I kind of rewrote your thing >_>;

I made a shit ton of atomic reviewable commits :)
## Highlights
- documentation in README
- full code coverage tests
- Fix nasty bug about instanceof & node_modules :(
- Changed it to return `undefined` so you can box `null` in a `Result.Ok`
- gaurd against boxing the wrong things.

### CODE REVIEW

**Comment by Raynos** [comment]
BTW because i set the major version number in the source code to 1 you should `npm version major && npm publish` after merging.

**Comment by Raynos** [comment]
I just updated this PR with some more commits.
- Fixed up example.js. forgot to update it.
- Added an `isOk` and `isErr` function because I'm afraid I'll forget to type `!== undefined`

Once i started using this library in other modules I immediately wanted an `isOk` and `isErr` helper because I noticed I accidentally forgot to type `!== undefined` and introduced a subtle bug.

**Comment by mmalecki** [comment]
Love it! Thanks for making this an actually usable module instead of a wild hack! Everything LGTM besides those minor nitpicks.

**Comment by mmalecki** [comment]
(Also just added you as a collaborator)

**Comment by Raynos** [comment]
@mmalecki finally got around to those changes :)

**Comment by Raynos** [comment]
I created a v1.0.0 on the master branch.

Would you mind publishing this module :)

**Pull request merged**
